# Generated by Django 2.1.2 on 2018-12-16 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_comment_id', models.IntegerField(default=-1, null=True)),
                ('star', models.FloatField(null=True)),
                ('content', models.TextField(null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='first published date')),
                ('last_modify_date', models.DateTimeField(auto_now=True, verbose_name='last edited date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Post')),
            ],
        ),
    ]
