# Generated by Django 2.1.2 on 2018-12-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='refer_comment',
            field=models.IntegerField(null=True),
        ),
    ]
