# Generated by Django 2.1.2 on 2018-12-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_comment_refer_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='refer_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='refer_comment_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
