# Generated by Django 2.1.2 on 2018-11-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_employer_introduction_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_preference',
            name='region',
            field=models.CharField(choices=[('교내', 'School'), ('설입', 'SNUStation'), ('녹두', 'Nokdu'), ('낙성대', 'Nakdae'), ('기타', 'Extra')], max_length=50, null=True),
        ),
    ]
