# Generated by Django 2.1.2 on 2018-12-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20181214_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_same_person',
            field=models.BooleanField(default=False),
        ),
    ]
