# Generated by Django 2.1.1 on 2018-12-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20181214_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=False),
        ),
    ]
