# Generated by Django 2.1.2 on 2018-12-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20181216_2004'),
        ('Post', '0006_post_author_name'),
    ]

    operations = [
    ]
