# Generated by Django 2.1.2 on 2018-11-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.TextField(null=True)),
                ('region', models.CharField(choices=[('교내', 'School'), ('설입', 'SNUStation'), ('녹두', 'Nokdu'), ('낙성대', 'Nakdae'), ('기타', 'Extra')], default='Extra', max_length=20)),
                ('arbeit_type', models.CharField(choices=[('멘토링', 'Mentoring'), ('과외', 'Tutoring'), ('카페', 'Cafe'), ('IT', 'IT'), ('디자인 알바', 'Design'), ('기타', 'Extra')], default='Extra', max_length=20)),
                ('pay', models.IntegerField(default=0)),
                ('manager_name', models.CharField(max_length=50, null=True)),
                ('manager_phone', models.CharField(max_length=50, null=True)),
                ('register_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('edit_date', models.DateTimeField(null=True, verbose_name='date edited')),
            ],
        ),
    ]
