# Generated by Django 2.1.2 on 2018-11-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arbeit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbeit',
            old_name='author_id',
            new_name='author',
        ),
    ]
