# Generated by Django 2.1.2 on 2018-11-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arbeit', '0003_auto_20181114_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeit',
            name='arbeit',
            field=models.CharField(choices=[('Mentoring', 'Mentoring'), ('Tutoring', 'Tutoring'), ('Cafe', 'Cafe'), ('IT', 'IT'), ('Design', 'Design'), ('Extra', 'Extra')], default='Extra', max_length=20),
        ),
        migrations.AlterField(
            model_name='arbeit',
            name='region',
            field=models.CharField(choices=[('School', 'School'), ('SNUStation', 'SNUStation'), ('Nokdu', 'Nokdu'), ('Nakdae', 'Nakdae'), ('Extra', 'Extra')], default='Extra', max_length=20),
        ),
    ]
