# Generated by Django 2.1.2 on 2018-11-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arbeit', '0004_auto_20181114_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbeit',
            old_name='arbeit',
            new_name='arbeit_type',
        ),
    ]
