# Generated by Django 2.1.2 on 2018-11-14 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arbeit', '0007_auto_20181114_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeit',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 4, 53, 48, 835495), verbose_name='date published'),
        ),
    ]
