# Generated by Django 2.1.2 on 2018-11-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arbeit', '0009_auto_20181114_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeit',
            name='edit_date',
            field=models.DateTimeField(null=True, verbose_name='date edited'),
        ),
        migrations.AlterField(
            model_name='arbeit',
            name='register_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
