# Generated by Django 2.1.2 on 2018-11-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arbeit', '0011_auto_20181114_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeit',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='arbeit',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
