# Generated by Django 2.1.2 on 2018-11-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arbeit', '0012_auto_20181114_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeit',
            name='arbeit_type',
            field=models.CharField(choices=[('멘토링', 'Mentoring'), ('과외', 'Tutoring'), ('카페', 'Cafe'), ('IT', 'IT'), ('디자인 알바', 'Design'), ('기타', 'Extra')], default='Extra', max_length=20),
        ),
        migrations.AlterField(
            model_name='arbeit',
            name='region',
            field=models.CharField(choices=[('교내', 'School'), ('설입', 'SNUStation'), ('녹두', 'Nokdu'), ('낙성대', 'Nakdae'), ('기타', 'Extra')], default='Extra', max_length=20),
        ),
    ]
