# Generated by Django 2.1.2 on 2018-11-28 16:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', django_mysql.models.EnumField(choices=[('EE', 'EE'), ('ER', 'ER')])),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('employee_region', django_mysql.models.EnumField(choices=[('seoulip', 'seoulip'), ('nakdae', 'nakdae'), ('nokdu', 'nokdu'), ('snu', 'snu'), ('home', 'home')], null=True)),
                ('employee_type', django_mysql.models.EnumField(choices=[('work_scholarship_student', 'work_scholarship_student'), ('mentoring', 'mentoring'), ('experiment_arbeit', 'experiment_arbeit'), ('private_lesson', 'private_lesson'), ('academy', 'academy'), ('survey', 'survey'), ('lecture', 'lecture'), ('service', 'service'), ('typing', 'typing'), ('outsourcing', 'outsourcing'), ('extra', 'extra')], null=True)),
                ('employee_how_to_pay', django_mysql.models.EnumField(choices=[('pay_hourly', 'pay_hourly'), ('pay_per_work', 'pay_per_work'), ('goods', 'goods'), ('random', 'random'), ('uncertain', 'uncertain')], null=True)),
                ('employee_pay_limit', models.IntegerField(null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('company_address', models.CharField(max_length=200, null=True)),
                ('business_content', models.TextField(null=True)),
                ('representative_name', models.CharField(max_length=50, null=True)),
                ('employer_license_number', models.CharField(max_length=20, null=True)),
                ('profile_image', models.ImageField(upload_to='uploads/')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
