# Generated by Django 2.1.2 on 2018-12-16 15:30

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', django_mysql.models.EnumField(choices=[('EE', 'EE'), ('ER', 'ER')])),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='email address')),
                ('nickname', models.CharField(max_length=50, null=True, unique=True)),
                ('employee_region', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=55, null=True, size=5)),
                ('employee_type', django_mysql.models.ListCharField(models.CharField(max_length=25), max_length=286, null=True, size=11)),
                ('employee_how_to_pay', django_mysql.models.ListCharField(models.CharField(max_length=15), max_length=80, null=True, size=5)),
                ('employee_pay_limit', models.PositiveIntegerField(null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('company_address', models.CharField(max_length=200, null=True)),
                ('business_content', models.TextField(null=True)),
                ('representative_name', models.CharField(max_length=50, null=True)),
                ('employer_license_number', models.CharField(max_length=20, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
