# Generated by Django 2.1.2 on 2018-12-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
