# Generated by Django 2.1.2 on 2018-11-28 17:47

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20181129_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=django_mysql.models.EnumField(choices=[('EE', 'EE'), ('ER', 'ER')]),
        ),
    ]
