# Generated by Django 2.1.4 on 2018-12-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20181207_2354'),
        ('User', '0002_remove_user_profile_image'),
    ]

    operations = [
    ]
